In [1]:
spark

In [2]:
df = spark.read.option('encoding', 'UTF-8').csv('hdfs:///tmp/dcd/sirilo', inferSchema = True, header = True)

In [3]:
df.count()

2097150

In [4]:
df.printSchema()

root
 |-- FOLIO: string (nullable = true)
 |-- FECHA_ALTA: string (nullable = true)
 |-- A�O_ALTA: integer (nullable = true)
 |-- MES_ALTA: integer (nullable = true)
 |-- D�A_ALTA: integer (nullable = true)
 |-- HORA_ALTA: integer (nullable = true)
 |-- SEXO: string (nullable = true)
 |-- EDAD: integer (nullable = true)
 |-- ESTADO_CIVIL: string (nullable = true)
 |-- OCUPACION: string (nullable = true)
 |-- ESCOLARIDAD: string (nullable = true)
 |-- ESTADO_USUARIA: string (nullable = true)
 |-- MUNICIPIO_USUARIA: string (nullable = true)
 |-- COLONIA_USUARIA: string (nullable = true)
 |-- CP_USUARIA: string (nullable = true)
 |-- ESTADO_HECHOS: string (nullable = true)
 |-- MUNICIPIO_HECHOS: string (nullable = true)
 |-- COLONIA_HECHOS: string (nullable = true)
 |-- CP_HECHOS: string (nullable = true)
 |-- ORIGEN: string (nullable = true)
 |-- SERVICIO: string (nullable = true)
 |-- TEMATICA_1: string (nullable = true)
 |-- TEMATICA_2: string (nullable = true)
 |-- TEMATICA_3: string (nullable = true)
 |-- TEMATICA_4: string (nullable = true)
 |-- TEMATICA_5: string (nullable = true)
 |-- TEMATICA_6: string (nullable = true)
 |-- TEMATICA_7: string (nullable = true)

In [5]:
df.columns

['FOLIO',
 'FECHA_ALTA',
 'A�O_ALTA',
 'MES_ALTA',
 'D�A_ALTA',
 'HORA_ALTA',
 'SEXO',
 'EDAD',
 'ESTADO_CIVIL',
 'OCUPACION',
 'ESCOLARIDAD',
 'ESTADO_USUARIA',
 'MUNICIPIO_USUARIA',
 'COLONIA_USUARIA',
 'CP_USUARIA',
 'ESTADO_HECHOS',
 'MUNICIPIO_HECHOS',
 'COLONIA_HECHOS',
 'CP_HECHOS',
 'ORIGEN',
 'SERVICIO',
 'TEMATICA_1',
 'TEMATICA_2',
 'TEMATICA_3',
 'TEMATICA_4',
 'TEMATICA_5',
 'TEMATICA_6',
 'TEMATICA_7']

In [7]:
df.describe().show()

22/06/04 01:44:03 WARN org.apache.spark.sql.catalyst.util.package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+-------+------------------+----------+------------------+------------------+------------------+------------------+---------+------------------+------------+--------------------+---------------+--------------+-----------------+--------------------+------------------+--------------+----------------+--------------------+------------------+----------+-----------+----------+----------------+-------------+-------------+--------------------+---------------+--------------------+
|summary|             FOLIO|FECHA_ALTA|          A�O_ALTA|          MES_ALTA|          D�A_ALTA|         HORA_ALTA|     SEXO|              EDAD|ESTADO_CIVIL|           OCUPACION|    ESCOLARIDAD|ESTADO_USUARIA|MUNICIPIO_USUARIA|     COLONIA_USUARIA|        CP_USUARIA| ESTADO_HECHOS|MUNICIPIO_HECHOS|      COLONIA_HECHOS|         CP_HECHOS|    ORIGEN|   SERVICIO|TEMATICA_1|      TEMATICA_2|   TEMATICA_3|   TEMATICA_4|          TEMATICA_5|     TEMATICA_6|          TEMATICA_7|
+-------+------------------+----------+------------------+------------------+------------------+------------------+---------+------------------+------------+--------------------+---------------+--------------+-----------------+--------------------+------------------+--------------+----------------+--------------------+------------------+----------+-----------+----------+----------------+-------------+-------------+--------------------+---------------+--------------------+
|  count|           2097150|   2097150|           2097150|           2097150|           2097150|           2097150|  2097150|           2097150|     2097150|             2097150|        2097150|       2097150|          2097150|             2097150|           2097150|       2097150|         2097150|             2097150|           2097150|   2097150|    2097150|   2097150|         2097150|      2097150|      2097150|             2097150|        2097150|             2097150|
|   mean| 536942.8123798961|      null|2019.0859394893068| 6.456564384998689|15.713779176501442|13.710526190305892|     null| 42.83153136399399|        null|                null|           null|          null|             null|           1966.3125|19018.522461692814|          null|            null|              2001.0|18790.691586854944|      null|       null|      null|            null|         null|         null|                null|           null|                null|
| stddev|300337.36380507716|      null| 1.451327225659339|3.4720190003687503| 8.760155227324843| 5.784162272574255|     null|13.743572779270512|        null|                null|           null|          null|             null|   45.54574977515075|21047.791281983988|          null|            null|                 0.0|20811.796625277108|      null|       null|      null|            null|         null|         null|                null|           null|                null|
|    min|          1.00E+05|2016-11-01|              2016|                 1|                 1|                 0| FEMENINO|                 1|  CASADO (A)|         COMERCIANTE|   BACHILLERATO|AGUASCALIENTES|            ABAL�|"""""""Y"""" GRIE...|                -1|AGUASCALIENTES|           ABAL�|"""""""Y"""" GRIE...|              1000|  ASESOR�A|   JUR�DICO|ADICCIONES|ABANDONO ESCOLAR|1ER TRIMESTRE|   ACCIDENTAL|ABANDONAR MUEBLES...|       ALUMNO/A| ENFRENTAR VIOLENCIA|
|    max|                NA|2022-02-13|              2022|                12|                31|                23|MASCULINO|                99| UNI�N LIBRE|TRABAJO INDEPENDI...|SIN ESCOLARIDAD|     ZACATECAS|   �LVARO OBREG�N|�XITO ENSE�ANZA Y...|              null|     ZACATECAS|  �LVARO OBREG�N|�XITO ENSE�ANZA Y...|                NA|N�MERO 911|PSICOL�GICO| VIOLENCIA|            ZIKA|     ZOOFILIA|�REAS COMUNES|          VIOLACI�N |VECINOS/VECINAS|VALORACI�N MEDICA...|
+-------+------------------+----------+------------------+------------------+------------------+------------------+---------+------------------+------------+--------------------+---------------+--------------+-----------------+--------------------+------------------+--------------+----------------+--------------------+------------------+----------+-----------+----------+----------------+-------------+-------------+--------------------+---------------+--------------------+

In [10]:
df.describe('A�O_ALTA').show()

+-------+------------------+
|summary|          A�O_ALTA|
+-------+------------------+
|  count|           2097150|
|   mean|2019.0859394893068|
| stddev|1.4513272256593328|
|    min|              2016|
|    max|              2022|
+-------+------------------+

In [11]:
df.describe(['EDAD']).show()

+-------+-----------------+
|summary|             EDAD|
+-------+-----------------+
|  count|          2097150|
|   mean|42.83153136399399|
| stddev|13.74357277927051|
|    min|                1|
|    max|               99|
+-------+-----------------+

In [12]:
import pyspark.sql.functions as f

In [14]:
dfa = df.agg(*[f.count(f.when(f.isnull(c), c)).alias(c) for c in df.columns])
dfa.toPandas()

,FOLIO,FECHA_ALTA,A�O_ALTA,MES_ALTA,D�A_ALTA,HORA_ALTA,SEXO,EDAD,ESTADO_CIVIL,OCUPACION,...,CP_HECHOS,ORIGEN,SERVICIO,TEMATICA_1,TEMATICA_2,TEMATICA_3,TEMATICA_4,TEMATICA_5,TEMATICA_6,TEMATICA_7
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0